name: Code_I2
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=24.0
  - python=3.10.14
  - pip:
      - corrfitter==8.2
      - gvar==13.1
      - h5py==3.11.0
      - lsqfit==13.2.2
      - numpy==1.26.4
      - scipy==1.13.1
      - matplotlib==3.9.0
      - tqdm==4.66.4